version: '3'
services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/var/www/app:delegated
      - ./config/php:/usr/local/etc/php/custom.d:delegated
    depends_on:
      - database
    expose:
      - 9003
    environment:
      - PHP_INI_SCAN_DIR=/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d
  web:
    container_name: web
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app:delegated
      - ./config/webserver/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php
  database:
    container_name: database
    image: postgres:latest
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data:delegated
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_BD=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=potionapproaching
